name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verificando o repositório do Github
          uses: actions/checkout@v2

        - name: Instalando o node com a versão 14
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: instalando as dependências de package.json
          run: npm install

        - name: executando o lint para verificação de erros
          run: npm run lint  